### ISSUE TITLE
BakkesModSetup.exe Permission denied

### ISSUE THREAD

**Issue by AbiQuinn** [CrumblyLiquid/BakkesLinux#4]
protontricks -c ~/Downloads/BakkesModSetup.exe 252950

comes back with:
```
[abi@asahigaoka ~]$ protontricks -c ~/Downloads/BakkesModSetup.exe 252950
pressure-vessel-wrap[60448]: W: Binding directories that are located under "/usr/" is not supported!
setlocale "en_US.UTF-8": No such file or directory
pressure-vessel-locale-gen: Missing locale en_US.UTF-8
pressure-vessel-locale-gen: Generating locale en_GB.UTF-8...
pressure-vessel-locale-gen: Generated locale en_GB.UTF-8 successfully
pressure-vessel-locale-gen: Generating locale en_US.UTF-8...
pressure-vessel-locale-gen: Generated locale en_US.UTF-8 successfully
pressure-vessel-adverb[60499]: W: Container startup will be faster if missing locales are created at OS level
/bin/sh: line 1: /home/abi/Downloads/BakkesModSetup.exe: Permission denied
```

Any advice would be appreciated, I'm still quite new to linux tbh.

I tried 
`[abi@asahigaoka ~]$ sudo protontricks -c ~/Downloads/BakkesModSetup.exe 252950`
`Steam installation directory could not be found.`
and
`[abi@asahigaoka ~]$ sudo protontricks -c /home/abi/Downloads/BakkesModSetup.exe 252950`
`Steam installation directory could not be found.`

**Comment by AbiQuinn** [comment]
hmm I noticed in the install.sh file there was a line, chmod +x... so I did
`chmod +x /home/abi/Downloads/BakkesModSetup.exe` 
and that fixed my issue I think.

**Comment by CrumblyLiquid** [comment]
I've added a warning to the guide mentioning this (commit 76d136e).
Thank you!
