### ISSUE TITLE
File path getting split at the space in "Program Files"

### ISSUE THREAD

**Issue by AbiQuinn** [CrumblyLiquid/BakkesLinux#5]
`[abi@asahigaoka ~]$ protontricks -c "/home/abi/.steam/steam/steamapps/compatdata/252950/pfx/drive_c/Program Files/BakkesMod/BakkesMod.exe" 252950`
Kept giving me:
`/bin/sh: line 1: /home/abi/.steam/steam/steamapps/compatdata/252950/pfx/drive_c/Program: No such file or directory`

Solution was to use extra ' ':
`protontricks -c "'/home/abi/.steam/steam/steamapps/compatdata/252950/pfx/drive_c/Program Files/BakkesMod/BakkesMod.exe'" 252950`

**Comment by CrumblyLiquid** [comment]
Reading `protontricks --help` I found this:
```
-c COMMAND, --command COMMAND
                        Run a command in the game's installation directory with Wine-related environment variables set. The command is passed to the shell as-is without being escaped.
```
It's not escaping the command and that's why the extra quotes are required.
Fixed in 2e8d4c1.

Thank you!
